### ISSUE TITLE
Possible Entity bug in rotate function?

### ISSUE THREAD

**Issue by mr-kiesel** [autarch1024/zombie-ai#1]
In Entity.cpp:
```
//Rotate d radians counterclockwise
void Entity::rotate(double d) {

	if (d == 0 || turnSpeed == 0) return;
	if (d > 2*M_PI || d < -2*M_PI) d = fmod(d, 2*M_PI);
	if (d > turnSpeed || d < -turnSpeed) d = fmod(d, turnSpeed);

	rotation += d;
	rotation = fmod(rotation, 2*M_PI);
}

```
Is the line 
`if (d > turnSpeed || d < -turnSpeed) d = fmod(d, turnSpeed);`

performing the right function?  

As written, if turnSpeed is 2.5:

-  an attempt to rotate 2.5 becomes a turn of zero
-  an attempt to rotate 2.6 becomes a turn of 0.1

I propose:
```
//Rotate d radians counterclockwise
void Entity::rotate(double d) {

	if (d == 0 || turnSpeed == 0) return;
	if (d > 2*M_PI || d < -2*M_PI) d = fmod(d, 2*M_PI);
	if (d >  turnSpeed) d = turnSpeed;
	if (d < -turnSpeed) d = -turnSpeed;

	rotation += d;
	rotation = fmod(rotation, 2*M_PI);
}
```

**Comment by mr-kiesel** [comment]
I realized as I made the second issue that I might be suggesting changes when the behavior show is intended because of the neural network!  If so, I apologize for wasting your time.

**Comment by autarch1024** [comment]
It was intentional, but it's one of those things where it made sense at the time, but makes no sense in retrospect. I went ahead and changed it.
